---
abstract: "Perl API for MaxMind's GeoIP2 web services and databases"
author:
  - 'Dave Rolsky <drolsky@maxmind.com>'
  - 'Greg Oschwald <goschwald@maxmind.com>'
  - 'Olaf Alders <oalders@maxmind.com>'
build_requires:
  HTTP::Status: '0'
  IO::Compress::Gzip: '0'
  Path::Class: '0'
  Test::Fatal: '0'
  Test::More: '0.88'
  base: '0'
  utf8: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GeoIP2
requires:
  B: '0'
  Data::Dumper: '0'
  Data::Validate::IP: '0.24'
  Exporter: '0'
  Getopt::Long: '0'
  JSON: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  MIME::Base64: '0'
  MaxMind::DB::Reader: '1.000000'
  Moo: '0'
  Moo::Role: '0'
  Params::Validate: '0'
  Scalar::Util: '0'
  Sub::Quote: '0'
  Throwable::Error: '0'
  Try::Tiny: '0'
  URI: '0'
  lib: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/maxmind/GeoIP2-perl/issues
  repository: git://github.com/maxmind/GeoIP2-perl.git
version: '2.000000'
x_authority: cpan:MAXMIND
x_contributors:
  - 'Graham Knop <haarg@haarg.org>'
